### ISSUE TITLE
Auto-login bug

### ISSUE THREAD

**Issue by ProgrammingWizzard** [SkriptPL/SkriptLauncher#2]
SkriptLauncher Version: 1.2.8.70
OS: Windows 10
Comments: The error was not present before, only during an update when you try to automatically log the error occurred (despite giving good data).

**Comment by LosTigeros** [comment]
Auto-login uses `/refresh` endpoint of Mojang Authentication API.

If there is accessToken invalidated, you will not get logged in.

Old accessToken is invalidated when You logging in. Then launcher gets new accessToken which will be used in future logging in process.
If someone was logged in in other place than on launcher on Your PC, then accessToken which launcher use to '/refresh' is already invalidated and You will not be logged in.

**Comment by ProgrammingWizzard** [comment]
Ok, thanks :)
